apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave-notebook
  labels:
    app: wave-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave-notebook
  template:
    metadata:
      labels:
        app: wave-notebook
    spec:
      containers:
      - name: wave-notebook
        image: cschranz/gpu-jupyter
        ports:
        - containerPort: 8888
        resources:
          limits:
            memory: 12Gi
            cpu: "8"
            nvidia.com/gpu: 1
          requests:
            memory: 12Gi
            cpu: "8"
        volumeMounts:
        - mountPath: /motiondata
          name: motiondata
      volumes:
        - name: motiondata
          persistentVolumeClaim:
            claimName: motiondata
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: gpu-type
      #          operator: In
      #          values:
      #          - 1080Ti
