apiVersion: apps/v1
kind: Deployment
metadata:
  name: # put deployment name here
  labels:
    app: # put deployment name here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: # put deployment name here
  template:
    metadata:
      labels:
        app: # put deployment name here
    spec:
      containers:
      - name: # put deployment name here
        image: cschranz/gpu-jupyter
        ports:
        - containerPort: 8888
        resources:
          limits: # minimum resources
            memory: 1Gi
            cpu: "4"
            # nvidia.com/gpu: 1 # uncomment to request at least 1 GPU
          requests: # max resources
            memory: 1Gi
            cpu: "4"
        volumeMounts:
        - mountPath: /motiondata
          name: motiondata
      volumes:
        - name: motiondata
          persistentVolumeClaim:
            claimName: motiondata
      # Uncomment block to specify type of GPU
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: gpu-type
      #          operator: In
      #          values:
      #          - 1080Ti
